package com.ad.util.tag;

public class SampleTagMraid {

  public static String getSampleMraid() {

    String s = "function mraidIsReady() {\n"
        + "    mraid.removeEventListener(\"ready\", mraidIsReady);\n"
        + "    prepareMyAd();\n"
        + "}\n"
        + "\n"
        + "function prepareMyAd() {\n"
        + "    if (!mraid.isViewable()) {\n"
        + "        mraid.addEventListener(\"viewableChange\", isInterstitialDisplayed);\n"
        + "    } else {\n"
        + "        showMyAd();\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function isInterstitialDisplayed(displayed) {\n"
        + "    if (displayed) {\n"
        + "        mraid.removeEventListener(\"viewableChange\", isInterstitialDisplayed);\n"
        + "        showMyAd();\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function showMyAd() {\n"
        + "    var img = document.querySelector('#img1');\n"
        + "    img.style.display = \"block\";\n"
        + "    if (img.complete && img.naturalHeight !== 0) {\n"
        + "        eventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=2\");\n"
        + "    }\n"
        + "    attachEventListener(\"click\", img, function(e) {\n"
        + "        e.preventDefault();\n"
        + "        mraid.open('http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/clk?guid={TAG_GUID}&sessionId={SESSION_ID}');\n"
        + "        return false;\n"
        + "    });\n"
        + "    attachEventListener(\"error\", img, function(e) {\n"
        + "        e.preventDefault();\n"
        + "        eventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=11\");\n"
        + "        return false;\n"
        + "    });\n"
        + "}\n"
        + "\n"
        + "function eventTrack(url) {\n"
        + "    var tracker = new Image();\n"
        + "    tracker.src = url;\n"
        + "}\n"
        + "\n"
        + "function setupViewport(width) {\n"
        + "    var element = document.querySelector(\"meta[name=viewport]\");\n"
        + "    if (!element) {\n"
        + "        element = document.createElement(\"meta\");\n"
        + "        element.name = \"viewport\";\n"
        + "        element.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "        document.getElementsByTagName('head')[0].appendChild(element);\n"
        + "    } else {\n"
        + "        element.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "    }\n"
        + "}\n"
        + "setupViewport(320);\n"
        + "\n"
        + "function attachEventListener(evt, el, fn) {\n"
        + "    if (el.addEventListener) {\n"
        + "        el.addEventListener(evt, fn, false);\n"
        + "    } else if (el.attachEvent) {\n"
        + "        el.attachEvent(\"on\" + evt, fn);\n"
        + "    } else {\n"
        + "        el[evt] = fn;\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function doReadyCheck() {\n"
        + "    if (!checkOnce) {\n"
        + "        checkOnce = true;\n"
        + "        if (mraid.getState() == 'loading') {\n"
        + "            mraid.addEventListener(\"ready\", mraidIsReady);\n"
        + "        } else {\n"
        + "            prepareMyAd();\n"
        + "        }\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function loadAd() {\n"
        + "    var elemDiv = document.createElement('div');\n"
        + "    elemDiv.setAttribute(\"id\", \"adContainer\");\n"
        + "    document.body.appendChild(elemDiv);\n"
        + "    var elemImg = new Image(320, 480);\n"
        + "    elemImg.id = 'img1';\n"
        + "    elemImg.onload = function() {\n"
        + "        // image loaded pixel \n"
        + "        eventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=1\");\n"
        + "        doReadyCheck();\n"
        + "    };\n"
        + "    elemImg.src = '{IMAGE_URL_1}';\n"
        + "    elemImg.style.cssText = \"display:none;position:absolute;top:0px;left:0px;\";\n"
        + "    elemDiv.appendChild(elemImg);\n"
        + "}\n"
        + "checkOnce = false;\n"
        + "setTimeout(doReadyCheck, 1000);\n"
        + "\n"
        + "loadAd();";

    return s;
  }

}
