package com.ad.util.tag;

public class SampleTagMraid {

  public static void main(String[] args) {

    String s = "<script src=\"mraid.js\"></script> \n"
        + "<script type=\"text/javascript\">\n"
        + "function mraidIsReady()\n"
        + "{\n"
        + "\tmraid.removeEventListener(\"ready\", mraidIsReady);\n"
        + "\t\n"
        + "\tprepareMyAd();\n"
        + "}\n"
        + "\n"
        + "function prepareMyAd()\n"
        + "{\t// fire loaded tracker  - fire any URL (Rajesh)\n"
        + "\tif (!mraid.isViewable())\n"
        + "\t{\n"
        + "\t\tmraid.addEventListener(\"viewableChange\", isInterstitialDisplayed); \n"
        + "\t}\n"
        + "\telse\n"
        + "\t{\n"
        + "\t\tshowMyAd();\n"
        + "\t}\n"
        + "}\n"
        + "\n"
        + "function isInterstitialDisplayed(displayed)\n"
        + "{\t\n"
        + "\tif (displayed)\n"
        + "\t{\n"
        + "\t\tmraid.removeEventListener(\"viewableChange\", isInterstitialDisplayed);\n"
        + "\t\tshowMyAd();\n"
        + "\t}\n"
        + "}\n"
        + "\n"
        + "function showMyAd()\n"
        + "{\n"
        + "    // Count impressions at this point and display ad - fire any sample URL (Rajesh)\n"
        + "\tvar el = document.getElementById(\"expanded\");\n"
        + "    el.style.display = '';\n"
        + "}\n"
        + "\n"
        + "function openSite(url)\n"
        + "{\n"
        + "\tmraid.open(url);\n"
        + "}\n"
        + "\n"
        + "function setupViewport(width)\n"
        + "{\n"
        + "\tvar element = document.querySelector(\"meta[name=viewport]\");\n"
        + "\tif (!element)\n"
        + "\t{\n"
        + "\t\telement = document.createElement(\"meta\");\n"
        + "\t\telement.name = \"viewport\";\n"
        + "\t\telement.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "\t\tdocument.getElementsByTagName('head')[0].appendChild(element);\n"
        + "\t}\n"
        + "\telse\n"
        + "\t{\n"
        + "\t\telement.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "\t}\n"
        + "}\n"
        + "setupViewport(320);\n"
        + "\n"
        + "function doReadyCheck()\n"
        + "{\t\n"
        + "\tif (mraid.getState() == 'loading') \n"
        + "\t{\t\n"
        + "\t\tmraid.addEventListener(\"ready\", mraidIsReady);  \n"
        + "\t} \n"
        + "\telse\n"
        + "\t{ \t\n"
        + "\t\tprepareMyAd();      \n"
        + "\t}\n"
        + "}\n"
        + "\n"
        + "doReadyCheck();\n"
        + "</script>\n"
        + "\n"
        + "<div id=\"adContainer\">\n"
        + "\t<div id=\"expanded\" style=\"display:none;width:320px;height:480px;margin:auto;position:relative;top:0px;left:0px;\">\n"
        + "\t\t<img width=\"320\" height=\"480\" style=\"position:absolute;top:0px;left:0px;\" src=\"https://s3.us-east-2.amazonaws.com/hyper-media-assets/creatives/UBR20609-2_Sweater_+40-1_sRGB_sh.jpg\" onclick=\"javascript:openSite('https://www.uber.com');\" />\t\t\n"
        + "\t</div>\n"
        + "</div>";
  }

}
