package com.ad.util.tag;

public class SampleTagMraid {

  public static String getSampleMraid() {

    String s = "<script src=\"mraid.js\"></script> \n"
        + "<script type=\"text/javascript\">\n"
        + "function mraidIsReady() {\n"
        + "    mraid.removeEventListener(\"ready\", mraidIsReady);\n"
        + "    prepareMyAd();\n"
        + "}\n"
        + "\n"
        + "function prepareMyAd() {\n"
        + "\t// image loaded pixel \n"
        + "\t eventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=1\");\n"
        + "    if (!mraid.isViewable()) {\n"
        + "        mraid.addEventListener(\"viewableChange\", isInterstitialDisplayed);\n"
        + "    } else {\n"
        + "        showMyAd();\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function isInterstitialDisplayed(displayed) {\n"
        + "    if (displayed) {\n"
        + "        mraid.removeEventListener(\"viewableChange\", isInterstitialDisplayed);\n"
        + "        showMyAd();\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "function showMyAd() {\n"
        + "    // Count impressions at this point and display ad  & Fire impression tracker \n"
        + "\tvar img = document.querySelector('#img1');\n"
        + "\timg.style.display = \"block\";\n"
        + "\tif(img.complete && img.naturalHeight !== 0) {\n"
        + "\t\teventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=2\");\n"
        + "\t}\n"
        + "\tattachEventListener(\"click\", img , function (e) {\n"
        + "\t\te.preventDefault();\n"
        + "\t\tmraid.open('http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/clk?guid={TAG_GUID}&sessionId={SESSION_ID}');\n"
        + "\t\treturn false;\n"
        + "\t});\n"
        + "\tattachEventListener(\"error\", img , function (e) {\n"
        + "\t\te.preventDefault();\n"
        + "\t\teventTrack(\"http://ec2-18-191-183-129.us-east-2.compute.amazonaws.com/trk?guid={TAG_GUID}&sessionId={SESSION_ID}&eventId=11\");\n"
        + "\t\treturn false;\n"
        + "\t});\n"
        + "}\n"
        + "\n"
        + "function eventTrack(url) {\n"
        + "\tvar tracker = new Image();\n"
        + "\ttracker.src = url;\n"
        + "}\n"
        + "\n"
        + "function setupViewport(width) {\n"
        + "    var element = document.querySelector(\"meta[name=viewport]\");\n"
        + "    if (!element) {\n"
        + "        element = document.createElement(\"meta\");\n"
        + "        element.name = \"viewport\";\n"
        + "        element.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "        document.getElementsByTagName('head')[0].appendChild(element);\n"
        + "    } else {\n"
        + "        element.content = \"width=\" + width + \", user-scalable=no\";\n"
        + "    }\n"
        + "}\n"
        + "setupViewport(320);\n"
        + "\n"
        + "function attachEventListener(evt, el, fn) {\n"
        + "\tif (el.addEventListener) {\n"
        + "\t\tel.addEventListener(evt, fn, false);\n"
        + "\t} else if (el.attachEvent) {\n"
        + "\t\tel.attachEvent(\"on\" + evt, fn);\n"
        + "\t} else {\n"
        + "\t\tel[evt] = fn;\n"
        + "\t}\n"
        + "}\n"
        + "\n"
        + "function doReadyCheck() {\n"
        + "    if (mraid.getState() == 'loading') {\n"
        + "        mraid.addEventListener(\"ready\", mraidIsReady);\n"
        + "    } else {\n"
        + "        prepareMyAd();\n"
        + "    }\n"
        + "}\n"
        + "\n"
        + "doReadyCheck();\n"
        + "</script>\n"
        + "\n"
        + "<div id=\"adContainer\">\n"
        + "\t<img id=\"img1\" width=\"320\" height=\"480\" style=\"display:none;position:absolute;top:0px;left:0px;\" src=\"https://s3.us-east-2.amazonaws.com/hyper-media-assets/creatives/UBR20609-2_Sweater_+40-1_sRGB_sh.jpg\" />\t\t\n"
        + "</div>";

    return s;
  }

}
