package com.ad.util.geo;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

/**
 * @author sagupta
 */

public class CountryCode {

  private static HashMap<String, String> codes = new HashMap<String, String>();
  private static HashMap<String, String> isoCountryName = new HashMap<String, String>();

  static {
    codes.put("AD", "AND");
    codes.put("AE", "ARE");
    codes.put("AF", "AFG");
    codes.put("AG", "ATG");
    codes.put("AI", "AIA");
    codes.put("AL", "ALB");
    codes.put("AM", "ARM");
    codes.put("AO", "AGO");
    codes.put("AQ", "ATA");
    codes.put("AR", "ARG");
    codes.put("AS", "ASM");
    codes.put("AT", "AUT");
    codes.put("AU", "AUS");
    codes.put("AW", "ABW");
    codes.put("AX", "ALA");
    codes.put("AZ", "AZE");
    codes.put("BA", "BIH");
    codes.put("BB", "BRB");
    codes.put("BD", "BGD");
    codes.put("BE", "BEL");
    codes.put("BF", "BFA");
    codes.put("BG", "BGR");
    codes.put("BH", "BHR");
    codes.put("BI", "BDI");
    codes.put("BJ", "BEN");
    codes.put("BL", "BLM");
    codes.put("BM", "BMU");
    codes.put("BN", "BRN");
    codes.put("BO", "BOL");
    codes.put("BQ", "BES");
    codes.put("BQ", "BQ");
    codes.put("BR", "BRA");
    codes.put("BS", "BHS");
    codes.put("BT", "BTN");
    codes.put("BW", "BWA");
    codes.put("BY", "BLR");
    codes.put("BZ", "BLZ");
    codes.put("CA", "CAN");
    codes.put("CC", "CCK");
    codes.put("CD", "COD");
    codes.put("CF", "CAF");
    codes.put("CG", "CG");
    codes.put("CG", "COG");
    codes.put("CH", "CHE");
    codes.put("CI", "CIV");
    codes.put("CK", "COK");
    codes.put("CL", "CHL");
    codes.put("CM", "CMR");
    codes.put("CN", "CHN");
    codes.put("CO", "COL");
    codes.put("CR", "CRI");
    codes.put("CU", "CUB");
    codes.put("CV", "CPV");
    codes.put("CW", "CUW");
    codes.put("CX", "CXR");
    codes.put("CY", "CYP");
    codes.put("CZ", "CZE");
    codes.put("DE", "DEU");
    codes.put("DJ", "DJI");
    codes.put("DK", "DNK");
    codes.put("DM", "DMA");
    codes.put("DO", "DOM");
    codes.put("DZ", "DZA");
    codes.put("EC", "ECU");
    codes.put("EE", "EST");
    codes.put("EG", "EGY");
    codes.put("ER", "ERI");
    codes.put("ES", "ESP");
    codes.put("ET", "ETH");
    codes.put("FI", "FIN");
    codes.put("FJ", "FJ");
    codes.put("FJ", "FJI");
    codes.put("FK", "FLK");
    codes.put("FM", "FSM");
    codes.put("FO", "FRO");
    codes.put("FR", "FRA");
    codes.put("GA", "GAB");
    codes.put("GB", "GBR");
    codes.put("GD", "GRD");
    codes.put("GE", "GEO");
    codes.put("GF", "GUF");
    codes.put("GG", "GGY");
    codes.put("GH", "GHA");
    codes.put("GI", "GIB");
    codes.put("GL", "GRL");
    codes.put("GM", "GMB");
    codes.put("GN", "GIN");
    codes.put("GP", "GLP");
    codes.put("GQ", "GNQ");
    codes.put("GR", "GRC");
    codes.put("GS", "SGS");
    codes.put("GT", "GTM");
    codes.put("GU", "GUM");
    codes.put("GW", "GNB");
    codes.put("GY", "GUY");
    codes.put("HK", "HKG");
    codes.put("HN", "HND");
    codes.put("HR", "HRV");
    codes.put("HT", "HTI");
    codes.put("HU", "HUN");
    codes.put("ID", "IDN");
    codes.put("IE", "IRL");
    codes.put("IL", "ISR");
    codes.put("IM", "IMN");
    codes.put("IN", "IND");
    codes.put("IO", "IOT");
    codes.put("IQ", "IRQ");
    codes.put("IR", "IRN");
    codes.put("IS", "ISL");
    codes.put("IT", "ITA");
    codes.put("JE", "JEY");
    codes.put("JM", "JAM");
    codes.put("JO", "JOR");
    codes.put("JP", "JPN");
    codes.put("KE", "KEN");
    codes.put("KG", "KGZ");
    codes.put("KH", "KHM");
    codes.put("KI", "KIR");
    codes.put("KM", "COM");
    codes.put("KN", "KNA");
    codes.put("KP", "PRK");
    codes.put("KR", "KOR");
    codes.put("KR", "KR");
    codes.put("KW", "KWT");
    codes.put("KY", "CYM");
    codes.put("KZ", "KAZ");
    codes.put("KZ", "KZ");
    codes.put("LA", "LAO");
    codes.put("LB", "LBN");
    codes.put("LC", "LCA");
    codes.put("LI", "LIE");
    codes.put("LK", "LKA");
    codes.put("LR", "LBR");
    codes.put("LS", "LSO");
    codes.put("LT", "LT");
    codes.put("LT", "LTU");
    codes.put("LU", "LUX");
    codes.put("LV", "LVA");
    codes.put("LY", "LBY");
    codes.put("MA", "MAR");
    codes.put("MC", "MCO");
    codes.put("MD", "MD");
    codes.put("MD", "MDA");
    codes.put("ME", "MNE");
    codes.put("MF", "MAF");
    codes.put("MG", "MDG");
    codes.put("MH", "MHL");
    codes.put("MK", "MKD");
    codes.put("ML", "MLI");
    codes.put("MM", "MM");
    codes.put("MM", "MMR");
    codes.put("MN", "MNG");
    codes.put("MO", "MAC");
    codes.put("MP", "MNP");
    codes.put("MQ", "MTQ");
    codes.put("MR", "MRT");
    codes.put("MS", "MSR");
    codes.put("MT", "MLT");
    codes.put("MU", "MUS");
    codes.put("MV", "MDV");
    codes.put("MW", "MWI");
    codes.put("MX", "MEX");
    codes.put("MY", "MYS");
    codes.put("MZ", "MOZ");
    codes.put("NA", "NAM");
    codes.put("NC", "NCL");
    codes.put("NE", "NER");
    codes.put("NF", "NFK");
    codes.put("NG", "NGA");
    codes.put("NI", "NIC");
    codes.put("NL", "NLD");
    codes.put("NO", "NOR");
    codes.put("NP", "NPL");
    codes.put("NR", "NRU");
    codes.put("NU", "NIU");
    codes.put("NZ", "NZL");
    codes.put("OM", "OMN");
    codes.put("PA", "PAN");
    codes.put("PE", "PER");
    codes.put("PF", "PYF");
    codes.put("PG", "PNG");
    codes.put("PH", "PHL");
    codes.put("PK", "PAK");
    codes.put("PL", "POL");
    codes.put("PM", "SPM");
    codes.put("PN", "PCN");
    codes.put("PR", "PRI");
    codes.put("PS", "PSE");
    codes.put("PT", "PRT");
    codes.put("PW", "PLW");
    codes.put("PY", "PRY");
    codes.put("QA", "QAT");
    codes.put("RE", "REU");
    codes.put("RO", "ROU");
    codes.put("RS", "SRB");
    codes.put("RU", "RU");
    codes.put("RU", "RUS");
    codes.put("RW", "RWA");
    codes.put("SA", "SAU");
    codes.put("SB", "SLB");
    codes.put("SC", "SYC");
    codes.put("SD", "SDN");
    codes.put("SE", "SWE");
    codes.put("SG", "SGP");
    codes.put("SH", "SHN");
    codes.put("SI", "SVN");
    codes.put("SJ", "SJM");
    codes.put("SK", "SK");
    codes.put("SK", "SVK");
    codes.put("SL", "SLE");
    codes.put("SM", "SMR");
    codes.put("SN", "SEN");
    codes.put("SO", "SOM");
    codes.put("SR", "SUR");
    codes.put("SS", "SSD");
    codes.put("ST", "ST");
    codes.put("ST", "STP");
    codes.put("SV", "SLV");
    codes.put("SX", "SXM");
    codes.put("SY", "SYR");
    codes.put("SZ", "SWZ");
    codes.put("TC", "TCA");
    codes.put("TD", "TCD");
    codes.put("TF", "ATF");
    codes.put("TG", "TGO");
    codes.put("TH", "THA");
    codes.put("TJ", "TJK");
    codes.put("TK", "TKL");
    codes.put("TL", "TL");
    codes.put("TL", "TLS");
    codes.put("TM", "TKM");
    codes.put("TN", "TUN");
    codes.put("TO", "TON");
    codes.put("TR", "TUR");
    codes.put("TT", "TTO");
    codes.put("TV", "TUV");
    codes.put("TW", "TWN");
    codes.put("TZ", "TZA");
    codes.put("UA", "UKR");
    codes.put("UG", "UGA");
    codes.put("UM", "UMI");
    codes.put("US", "USA");
    codes.put("UY", "URY");
    codes.put("UZ", "UZB");
    codes.put("VA", "VAT");
    codes.put("VC", "VCT");
    codes.put("VE", "VEN");
    codes.put("VG", "VGB");
    codes.put("VI", "VI");
    codes.put("VI", "VIR");
    codes.put("VN", "VNM");
    codes.put("VU", "VUT");
    codes.put("WF", "WLF");
    codes.put("WS", "WSM");
    codes.put("XK", "UNK");
    codes.put("YE", "YEM");
    codes.put("YT", "MYT");
    codes.put("ZA", "ZAF");
    codes.put("ZM", "ZMB");
    codes.put("ZW", "ZWE");

    isoCountryName.put("ABW", "Aruba");
    isoCountryName.put("AFG", "Afghanistan");
    isoCountryName.put("AGO", "Angola");
    isoCountryName.put("AIA", "Anguilla");
    isoCountryName.put("ALA", "Aland Islands");
    isoCountryName.put("ALB", "Albania");
    isoCountryName.put("AND", "Andorra");
    isoCountryName.put("ARE", "United Arab Emirates");
    isoCountryName.put("ARG", "Argentina");
    isoCountryName.put("ARM", "Armenia");
    isoCountryName.put("ASM", "American Samoa");
    isoCountryName.put("ATA", "Antarctica");
    isoCountryName.put("ATF", "French Southern territories");
    isoCountryName.put("ATG", "Antigua and Barbuda");
    isoCountryName.put("AUS", "Australia");
    isoCountryName.put("AUT", "Austria");
    isoCountryName.put("AZE", "Azerbaijan");
    isoCountryName.put("BDI", "Burundi");
    isoCountryName.put("BEL", "Belgium");
    isoCountryName.put("BEN", "Benin");
    isoCountryName.put("BES", "Bonaire, Sint Eustatius, and Saba");
    isoCountryName.put("BFA", "Burkina Faso");
    isoCountryName.put("BGD", "Bangladesh");
    isoCountryName.put("BGR", "Bulgaria");
    isoCountryName.put("BHR", "Bahrain");
    isoCountryName.put("BHS", "Bahamas");
    isoCountryName.put("BIH", "Bosnia and Herzegovina");
    isoCountryName.put("BLM", "Saint Bartelemey");
    isoCountryName.put("BLR", "Belarus");
    isoCountryName.put("BLZ", "Belize");
    isoCountryName.put("BMU", "Bermuda");
    isoCountryName.put("BOL", "Bolivia");
    isoCountryName.put("BQ", "Bonaire, Sint Eustatius, and Saba");
    isoCountryName.put("BRA", "Brazil");
    isoCountryName.put("BRB", "Barbados");
    isoCountryName.put("BRN", "Brunei");
    isoCountryName.put("BTN", "Bhutan");
    isoCountryName.put("BWA", "Botswana");
    isoCountryName.put("CAF", "Central African Republic");
    isoCountryName.put("CAN", "Canada");
    isoCountryName.put("CCK", "Cocos [Keeling] Islands");
    isoCountryName.put("CG", "Republic of the Congo");
    isoCountryName.put("CHE", "Switzerland");
    isoCountryName.put("CHL", "Chile");
    isoCountryName.put("CHN", "China");
    isoCountryName.put("CIV", "Ivory Coast");
    isoCountryName.put("CMR", "Cameroon");
    isoCountryName.put("COD", "Congo");
    isoCountryName.put("COG", "Republic of the Congo");
    isoCountryName.put("COK", "Cook Islands");
    isoCountryName.put("COL", "Colombia");
    isoCountryName.put("COM", "Comoros");
    isoCountryName.put("CPV", "Cape Verde");
    isoCountryName.put("CRI", "Costa Rica");
    isoCountryName.put("CUB", "Cuba");
    isoCountryName.put("CUW", "Curaçao");
    isoCountryName.put("CXR", "Christmas Island");
    isoCountryName.put("CYM", "Cayman Islands");
    isoCountryName.put("CYP", "Cyprus");
    isoCountryName.put("CZE", "Czechia");
    isoCountryName.put("DEU", "Germany");
    isoCountryName.put("DJI", "Djibouti");
    isoCountryName.put("DMA", "Dominica");
    isoCountryName.put("DNK", "Denmark");
    isoCountryName.put("DOM", "Dominican Republic");
    isoCountryName.put("DZA", "Algeria");
    isoCountryName.put("ECU", "Ecuador");
    isoCountryName.put("EGY", "Egypt");
    isoCountryName.put("ERI", "Eritrea");
    isoCountryName.put("ESP", "Spain");
    isoCountryName.put("EST", "Estonia");
    isoCountryName.put("ETH", "Ethiopia");
    isoCountryName.put("FIN", "Finland");
    isoCountryName.put("FJ", "Fiji");
    isoCountryName.put("FJI", "Fiji");
    isoCountryName.put("FLK", "Falkland Islands");
    isoCountryName.put("FRA", "France");
    isoCountryName.put("FRO", "Faroe Islands");
    isoCountryName.put("FSM", "Federated States of Micronesia");
    isoCountryName.put("GAB", "Gabon");
    isoCountryName.put("GBR", "United Kingdom");
    isoCountryName.put("GEO", "Georgia");
    isoCountryName.put("GGY", "Guernsey");
    isoCountryName.put("GHA", "Ghana");
    isoCountryName.put("GIB", "Gibraltar");
    isoCountryName.put("GIN", "Guinea");
    isoCountryName.put("GLP", "Guadeloupe");
    isoCountryName.put("GMB", "Gambia");
    isoCountryName.put("GNB", "Guinea-Bissau");
    isoCountryName.put("GNQ", "Equatorial Guinea");
    isoCountryName.put("GRC", "Greece");
    isoCountryName.put("GRD", "Grenada");
    isoCountryName.put("GRL", "Greenland");
    isoCountryName.put("GTM", "Guatemala");
    isoCountryName.put("GUF", "French Guiana");
    isoCountryName.put("GUM", "Guam");
    isoCountryName.put("GUY", "Guyana");
    isoCountryName.put("HKG", "Hong Kong");
    isoCountryName.put("HND", "Honduras");
    isoCountryName.put("HRV", "Croatia");
    isoCountryName.put("HTI", "Haiti");
    isoCountryName.put("HUN", "Hungary");
    isoCountryName.put("IDN", "Indonesia");
    isoCountryName.put("IMN", "Isle of Man");
    isoCountryName.put("IND", "India");
    isoCountryName.put("IOT", "British Indian Ocean Territory");
    isoCountryName.put("IRL", "Ireland");
    isoCountryName.put("IRN", "Iran");
    isoCountryName.put("IRQ", "Iraq");
    isoCountryName.put("ISL", "Iceland");
    isoCountryName.put("ISR", "Israel");
    isoCountryName.put("ITA", "Italy");
    isoCountryName.put("JAM", "Jamaica");
    isoCountryName.put("JEY", "Jersey");
    isoCountryName.put("JOR", "Hashemite Kingdom of Jordan");
    isoCountryName.put("JPN", "Japan");
    isoCountryName.put("KAZ", "Kazakhstan");
    isoCountryName.put("KEN", "Kenya");
    isoCountryName.put("KGZ", "Kyrgyzstan");
    isoCountryName.put("KHM", "Cambodia");
    isoCountryName.put("KIR", "Kiribati");
    isoCountryName.put("KNA", "Saint Kitts and Nevis");
    isoCountryName.put("KOR", "Republic of Korea");
    isoCountryName.put("KR", "Republic of Korea");
    isoCountryName.put("KWT", "Kuwait");
    isoCountryName.put("KZ", "Kazakhstan");
    isoCountryName.put("LAO", "Laos");
    isoCountryName.put("LBN", "Lebanon");
    isoCountryName.put("LBR", "Liberia");
    isoCountryName.put("LBY", "Libya");
    isoCountryName.put("LCA", "Saint Lucia");
    isoCountryName.put("LIE", "Liechtenstein");
    isoCountryName.put("LKA", "Sri Lanka");
    isoCountryName.put("LSO", "Lesotho");
    isoCountryName.put("LT", "Republic of Lithuania");
    isoCountryName.put("LTU", "Republic of Lithuania");
    isoCountryName.put("LUX", "Luxembourg");
    isoCountryName.put("LVA", "Latvia");
    isoCountryName.put("MAC", "Macao");
    isoCountryName.put("MAF", "Saint Martin");
    isoCountryName.put("MAR", "Morocco");
    isoCountryName.put("MCO", "Monaco");
    isoCountryName.put("MD", "Republic of Moldova");
    isoCountryName.put("MDA", "Republic of Moldova");
    isoCountryName.put("MDG", "Madagascar");
    isoCountryName.put("MDV", "Maldives");
    isoCountryName.put("MEX", "Mexico");
    isoCountryName.put("MHL", "Marshall Islands");
    isoCountryName.put("MKD", "Macedonia");
    isoCountryName.put("MLI", "Mali");
    isoCountryName.put("MLT", "Malta");
    isoCountryName.put("MM", "Myanmar [Burma]");
    isoCountryName.put("MMR", "Myanmar [Burma]");
    isoCountryName.put("MNE", "Montenegro");
    isoCountryName.put("MNG", "Mongolia");
    isoCountryName.put("MNP", "Northern Mariana Islands");
    isoCountryName.put("MOZ", "Mozambique");
    isoCountryName.put("MRT", "Mauritania");
    isoCountryName.put("MSR", "Montserrat");
    isoCountryName.put("MTQ", "Martinique");
    isoCountryName.put("MUS", "Mauritius");
    isoCountryName.put("MWI", "Malawi");
    isoCountryName.put("MYS", "Malaysia");
    isoCountryName.put("MYT", "Mayotte");
    isoCountryName.put("NAM", "Namibia");
    isoCountryName.put("NCL", "New Caledonia");
    isoCountryName.put("NER", "Niger");
    isoCountryName.put("NFK", "Norfolk Island");
    isoCountryName.put("NGA", "Nigeria");
    isoCountryName.put("NIC", "Nicaragua");
    isoCountryName.put("NIU", "Niue");
    isoCountryName.put("NLD", "Netherlands");
    isoCountryName.put("NOR", "Norway");
    isoCountryName.put("NPL", "Nepal");
    isoCountryName.put("NRU", "Nauru");
    isoCountryName.put("NZL", "New Zealand");
    isoCountryName.put("OMN", "Oman");
    isoCountryName.put("PAK", "Pakistan");
    isoCountryName.put("PAN", "Panama");
    isoCountryName.put("PCN", "Pitcairn Islands");
    isoCountryName.put("PER", "Peru");
    isoCountryName.put("PHL", "Philippines");
    isoCountryName.put("PLW", "Palau");
    isoCountryName.put("PNG", "Papua New Guinea");
    isoCountryName.put("POL", "Poland");
    isoCountryName.put("PRI", "Puerto Rico");
    isoCountryName.put("PRK", "North Korea");
    isoCountryName.put("PRT", "Portugal");
    isoCountryName.put("PRY", "Paraguay");
    isoCountryName.put("PSE", "Palestine");
    isoCountryName.put("PYF", "French Polynesia");
    isoCountryName.put("QAT", "Qatar");
    isoCountryName.put("REU", "Réunion");
    isoCountryName.put("ROU", "Romania");
    isoCountryName.put("RU", "Russia");
    isoCountryName.put("RUS", "Russia");
    isoCountryName.put("RWA", "Rwanda");
    isoCountryName.put("SAU", "Saudi Arabia");
    isoCountryName.put("SDN", "Sudan");
    isoCountryName.put("SEN", "Senegal");
    isoCountryName.put("SGP", "Singapore");
    isoCountryName.put("SGS",
        "South Georgia and the South Sandwich Islands");
    isoCountryName.put("SHN", "Saint Helena");
    isoCountryName.put("SJM", "Svalbard and Jan Mayen");
    isoCountryName.put("SK", "Slovak Republic");
    isoCountryName.put("SLB", "Solomon Islands");
    isoCountryName.put("SLE", "Sierra Leone");
    isoCountryName.put("SLV", "El Salvador");
    isoCountryName.put("SMR", "San Marino");
    isoCountryName.put("SOM", "Somalia");
    isoCountryName.put("SPM", "Saint Pierre and Miquelon");
    isoCountryName.put("SRB", "Serbia");
    isoCountryName.put("SSD", "South Sudan");
    isoCountryName.put("ST", "SÃ£o TomÃ© and PrÃ­ncipe");
    isoCountryName.put("STP", "Sao Tome and Principe");
    isoCountryName.put("SUR", "Suriname");
    isoCountryName.put("SVK", "Slovak Republic");
    isoCountryName.put("SVN", "Slovenia");
    isoCountryName.put("SWE", "Sweden");
    isoCountryName.put("SWZ", "Swaziland");
    isoCountryName.put("SXM", "Sint Maarten");
    isoCountryName.put("SYC", "Seychelles");
    isoCountryName.put("SYR", "Syria");
    isoCountryName.put("TCA", "Turks and Caicos Islands");
    isoCountryName.put("TCD", "Chad");
    isoCountryName.put("TGO", "Togo");
    isoCountryName.put("THA", "Thailand");
    isoCountryName.put("TJK", "Tajikistan");
    isoCountryName.put("TKL", "Tokelau");
    isoCountryName.put("TKM", "Turkmenistan");
    isoCountryName.put("TL", "East Timor");
    isoCountryName.put("TLS", "East Timor");
    isoCountryName.put("TON", "Tonga");
    isoCountryName.put("TTO", "Trinidad and Tobago");
    isoCountryName.put("TUN", "Tunisia");
    isoCountryName.put("TUR", "Turkey");
    isoCountryName.put("TUV", "Tuvalu");
    isoCountryName.put("TWN", "Taiwan");
    isoCountryName.put("TZA", "Tanzania");
    isoCountryName.put("UGA", "Uganda");
    isoCountryName.put("UKR", "Ukraine");
    isoCountryName.put("UMI", "U.S. Minor Outlying Islands");
    isoCountryName.put("UNK", "Kosovo");
    isoCountryName.put("URY", "Uruguay");
    isoCountryName.put("USA", "United States");
    isoCountryName.put("UZB", "Uzbekistan");
    isoCountryName.put("VAT", "Vatican City");
    isoCountryName.put("VCT", "Saint Vincent and the Grenadines");
    isoCountryName.put("VEN", "Venezuela");
    isoCountryName.put("VGB", "British Virgin Islands");
    isoCountryName.put("VI", "U.S. Virgin Islands");
    isoCountryName.put("VIR", "U.S. Virgin Islands");
    isoCountryName.put("VNM", "Vietnam");
    isoCountryName.put("VUT", "Vanuatu");
    isoCountryName.put("WLF", "Wallis and Futuna");
    isoCountryName.put("WSM", "Samoa");
    isoCountryName.put("YEM", "Yemen");
    isoCountryName.put("ZAF", "South Africa");
    isoCountryName.put("ZMB", "Zambia");
    isoCountryName.put("ZWE", "Zimbabwe");

  }

  /**
   *
   * @param isocode
   * @return
   */

  public static String getISO3CountryCode(String isocode) {
    return codes.get(isocode);
  }

  /**
   * @return country name
   */

  public static String getCountryFromIso3Code(String isocode) {
    return isoCountryName.get(isocode);
  }

  /**
   *
   * @return
   */
  public static Set<String> getAllIso3CountryCodes() {
    return new HashSet<String>(isoCountryName.keySet());
  }

}
