-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 17:56:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ad_server
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ad_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ad_server` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ad_server` ;

-- -----------------------------------------------------
-- Table `ad_server`.`account_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`account_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`account_type` (
  `account_type_id` INT NOT NULL,
  `account_type_label` VARCHAR(50) NOT NULL DEFAULT 'Advertiser',
  PRIMARY KEY (`account_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`address_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`address_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`address_type` (
  `address_type_id` INT NOT NULL,
  `address_type_desc` VARCHAR(50) NOT NULL DEFAULT 'Business',
  PRIMARY KEY (`address_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`address` (
  `address_id` INT NOT NULL,
  `address_type_id` INT NOT NULL,
  `address_line1` VARCHAR(250) NOT NULL,
  `address_line2` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `postal_code_id` INT NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `addr_addr_type_fk_idx` ON `ad_server`.`address` (`address_type_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`status` (
  `status_id` INT NOT NULL,
  `status_desc` VARCHAR(50) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`account` (
  `account_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `account_guid` VARCHAR(100) NOT NULL,
  `account_type_id` INT NOT NULL,
  `account_name` VARCHAR(100) NOT NULL,
  `account_email` VARCHAR(200) NOT NULL,
  `account_website` VARCHAR(500) NOT NULL,
  `address_id` INT NOT NULL,
  `logo_url` VARCHAR(500) NOT NULL,
  `time_zone_id` SMALLINT(6) NOT NULL,
  `currency_id` SMALLINT(6) NOT NULL,
  `status_id` INT NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `acc_type_fk_idx` ON `ad_server`.`account` (`account_type_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `acc_addr_fk_idx` ON `ad_server`.`account` (`address_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `acc_status_fk_idx` ON `ad_server`.`account` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`advertiser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`advertiser` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`advertiser` (
  `advertiser_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `advertiser_name` VARCHAR(100) NOT NULL,
  `advertiser_email` VARCHAR(200) NOT NULL,
  `advertiser_website` VARCHAR(500) NOT NULL,
  `address_id` INT NOT NULL,
  `logo_url` VARCHAR(500) NOT NULL,
  `time_zone_id` SMALLINT(6) NOT NULL,
  `currency_id` SMALLINT(6) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`advertiser_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `acc_adv_fk_idx` ON `ad_server`.`advertiser` (`account_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `adv_addr_fk_idx` ON `ad_server`.`advertiser` (`address_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `adv_status_fk_idx` ON `ad_server`.`advertiser` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`roles` (
  `role_id` INT NOT NULL,
  `role_type` VARCHAR(50) NOT NULL DEFAULT 'Trafficker',
  `role_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`user` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `password_salt` VARCHAR(50) NULL,
  `profile_photo_file_manager_id` VARCHAR(200) NULL,
  `locale_id` VARCHAR(45) NULL,
  `last_login_ip_address` VARCHAR(50) NULL,
  `last_login_timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`billing_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`billing_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`billing_type` (
  `billing_type_id` INT NOT NULL,
  `billing_type_label` VARCHAR(50) NOT NULL DEFAULT 'ACH',
  PRIMARY KEY (`billing_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`user_roles` (
  `user_roles_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`user_roles_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `user_roles_fk1_idx` ON `ad_server`.`user_roles` (`user_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `user_roles_fk2_idx` ON `ad_server`.`user_roles` (`roles_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `user_roles_fk3_idx` ON `ad_server`.`user_roles` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`user_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`user_accounts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`user_accounts` (
  `user_accounts_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `user_role_id` INT NOT NULL,
  `status_id` INT NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `user_accounts_fk1_idx` ON `ad_server`.`user_accounts` (`account_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `user_accounts_fk3_idx` ON `ad_server`.`user_accounts` (`status_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `user_accounts_fk2_idx` ON `ad_server`.`user_accounts` (`user_role_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`custom_attributes_keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`custom_attributes_keys` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`custom_attributes_keys` (
  `custom_attributes_id` INT NOT NULL,
  `key_name` VARCHAR(100) NOT NULL,
  `kay_label` VARCHAR(150) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`custom_attributes_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `csattr_keys_fk_idx` ON `ad_server`.`custom_attributes_keys` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`custom_attributes_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`custom_attributes_values` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`custom_attributes_values` (
  `custom_attributes_values_id` INT NOT NULL,
  `key_id` INT NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`custom_attributes_values_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `csattr_values_fk_idx` ON `ad_server`.`custom_attributes_values` (`key_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`billing_cycle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`billing_cycle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`billing_cycle` (
  `billing_cycle_id` INT NOT NULL,
  `billing_cycle_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`billing_cycle_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`billing_payment_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`billing_payment_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`billing_payment_details` (
  `billing_payment_details_id` INT NOT NULL,
  `billing_id` INT NOT NULL,
  `billing_type_id` INT NOT NULL,
  `bank_name` VARCHAR(100) NULL,
  `bank_account_number` INT NULL,
  `bank_routing_number` INT NULL,
  `credit_card_number` INT NULL,
  `credit_card_expiry_date` VARCHAR(45) NULL,
  `credit_card_cvv` VARCHAR(45) NULL,
  `billing_cycle_id` INT NULL,
  `billing_date` DATETIME NULL,
  PRIMARY KEY (`billing_payment_details_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `billing_cycle_fk_idx` ON `ad_server`.`billing_payment_details` (`billing_cycle_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `billing_type_fk_idx` ON `ad_server`.`billing_payment_details` (`billing_type_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`billing` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`billing` (
  `billing_id` INT NOT NULL,
  `billing_owner_id` INT NOT NULL,
  `billing_payment_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`billing_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `billing_user_fk_idx` ON `ad_server`.`billing` (`billing_owner_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `billing_status_fk_idx` ON `ad_server`.`billing` (`status_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `billing_payment_id_idx` ON `ad_server`.`billing` (`billing_payment_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`ad_partner_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`ad_partner_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`ad_partner_type` (
  `ad_partner_type_id` INT NOT NULL,
  `ad_partner_desc` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ad_partner_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`ad_partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`ad_partner` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`ad_partner` (
  `ad_partner_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address_id` INT NULL,
  `email` VARCHAR(200) NULL,
  `ad_partner_type_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`ad_partner_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `ad_partner_type_fk_idx` ON `ad_server`.`ad_partner` (`ad_partner_type_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `ad_partner_status_fk_idx` ON `ad_server`.`ad_partner` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`events` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`events` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(50) NOT NULL,
  `event_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`account_event_trackers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`account_event_trackers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`account_event_trackers` (
  `account_event_tracker_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `tracker_url` VARCHAR(250) NOT NULL,
  `append_macros` TINYINT(1) NOT NULL DEFAULT 1,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`account_event_tracker_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `acc_trc_fk1_idx` ON `ad_server`.`account_event_trackers` (`account_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `acc_trc_fk2_idx` ON `ad_server`.`account_event_trackers` (`event_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `acc_trc_fk3_idx` ON `ad_server`.`account_event_trackers` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`advertiser_event_trackers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`advertiser_event_trackers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`advertiser_event_trackers` (
  `advertiser_tracker_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `advertiser_id` INT NOT NULL,
  `tracker_url` VARCHAR(250) NOT NULL,
  `append_macros` TINYINT(1) NOT NULL DEFAULT 1,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`advertiser_tracker_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `adv_trc_fk1_idx` ON `ad_server`.`advertiser_event_trackers` (`advertiser_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `adv_trc_fk2_idx` ON `ad_server`.`advertiser_event_trackers` (`event_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `adv_trc_fk3_idx` ON `ad_server`.`advertiser_event_trackers` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`objective_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`objective_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`objective_type` (
  `objective_type_id` INT NOT NULL,
  `objective_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`objective_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`target` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`target` (
  `target_id` INT NOT NULL,
  `target_name` VARCHAR(100) NULL,
  `by_os` VARCHAR(512) NULL,
  `by_day_part` VARCHAR(512) NULL,
  `by_segment` BLOB NULL,
  `by_geo` BLOB NULL,
  PRIMARY KEY (`target_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`campaign` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`campaign` (
  `campaign_id` INT NOT NULL,
  `advertiser_id` INT NOT NULL,
  `campaign_name` VARCHAR(200) NOT NULL,
  `objective_type_id` INT NOT NULL,
  `custom_attributes` VARCHAR(5000) NULL,
  `target_id` INT NOT NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`campaign_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `acc_campaign_fk_idx` ON `ad_server`.`campaign` (`advertiser_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `campaign_obj_fk_idx` ON `ad_server`.`campaign` (`objective_type_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `campaign_status_fk_idx` ON `ad_server`.`campaign` (`status_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `campaign_target_fk_idx` ON `ad_server`.`campaign` (`target_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_format` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_format` (
  `creative_format_id` INT NOT NULL,
  `format` VARCHAR(100) NULL,
  PRIMARY KEY (`creative_format_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_size` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_size` (
  `creative_size_id` INT NOT NULL,
  `size` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`creative_size_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative` (
  `creative_id` INT NOT NULL,
  `campaign_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `target_id` INT NOT NULL,
  `creative_size_id` INT NULL,
  `creative_format_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`creative_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `cr_cmp_fk_idx` ON `ad_server`.`creative` (`campaign_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `cr_format_fk_idx` ON `ad_server`.`creative` (`creative_format_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `cr_target_fk_idx` ON `ad_server`.`creative` (`target_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `cr_size_fk_idx` ON `ad_server`.`creative` (`creative_size_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `cr_status-fk_idx` ON `ad_server`.`creative` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`asset_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`asset_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`asset_type` (
  `asset_type_id` INT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `ext` VARCHAR(50) NULL,
  `mime` VARCHAR(50) NULL,
  PRIMARY KEY (`asset_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`asset_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`asset_size` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`asset_size` (
  `asset_size_id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`asset_size_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_assets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_assets` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_assets` (
  `creative_asset_id` INT NOT NULL,
  `creative_id` INT NOT NULL,
  `asset_size_id` INT NOT NULL,
  `asset_type_id` INT NOT NULL,
  `asset_url` VARCHAR(250) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`creative_asset_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `asset_cr_fk_idx` ON `ad_server`.`creative_assets` (`creative_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `asset_type_fk_idx` ON `ad_server`.`creative_assets` (`asset_type_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `asset_size_fk_idx` ON `ad_server`.`creative_assets` (`asset_size_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `asset_status_fk_idx` ON `ad_server`.`creative_assets` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`os` (
  `os_id` INT NOT NULL,
  `os_name` VARCHAR(50) NOT NULL,
  `os_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`os_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`day_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`day_part` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`day_part` (
  `day_part_id` INT NOT NULL,
  `day_part` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`day_part_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`segment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`segment` (
  `segment_id` INT NOT NULL,
  `segment_name` VARCHAR(100) NOT NULL,
  `partner_name` INT NOT NULL,
  `partner_segment_taxonomy_id` VARCHAR(45) NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`segment_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`country` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`country` (
  `country_id` INT NOT NULL,
  `geoname_id` TINYINT NOT NULL,
  `region_id` TINYINT NOT NULL,
  `currency_id` TINYINT NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `country_code_2` VARCHAR(2) NOT NULL,
  `country_name` VARCHAR(100) NOT NULL,
  `local_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`state` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`state` (
  `state_id` INT NOT NULL,
  `state_unique_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `state_long_namw` VARCHAR(100) NOT NULL,
  `state_code` VARCHAR(10) NOT NULL,
  `fips_code` VARCHAR(5) NOT NULL,
  `time_zone_id` TINYINT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `state_coun_fk_idx` ON `ad_server`.`state` (`country_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`city` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`city` (
  `city_id` INT NOT NULL,
  `geoname_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `city_name` VARCHAR(100) NOT NULL,
  `city_code` VARCHAR(5) NULL,
  `postal_code` VARCHAR(15) NULL,
  `census_data_dma_id` INT NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `city_state_fk_idx` ON `ad_server`.`city` (`state_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`postal_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`postal_code` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`postal_code` (
  `postal_code_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `postal_code` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`postal_code_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `postal_cc_city_fk_idx` ON `ad_server`.`postal_code` (`city_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_tag` (
  `creative_tag_id` INT NOT NULL,
  `ad_partner_id` INT NOT NULL,
  `tag_type_id` INT NOT NULL,
  `creative_id` INT NOT NULL,
  `tag_guid` VARCHAR(300) NOT NULL,
  `creative_markup_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`creative_tag_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`tag_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`tag_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`tag_type` (
  `tag_type_id` INT NOT NULL,
  `tag_type` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_group` (
  `creative_group_id` INT NOT NULL,
  `creative_group_name` VARCHAR(100) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`creative_group_id`, `creative_group_name`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `cr_group_status_fk_idx` ON `ad_server`.`creative_group` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`creative_group_coll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`creative_group_coll` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`creative_group_coll` (
  `creative_group_coll_id` INT NOT NULL,
  `creative_group_id` INT NOT NULL,
  `creative_id` INT NOT NULL,
  `distribution_percen` FLOAT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`creative_group_coll_id`, `creative_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `group_fk1_idx` ON `ad_server`.`creative_group_coll` (`creative_group_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `group_fk2_idx` ON `ad_server`.`creative_group_coll` (`creative_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `group_fk3_idx` ON `ad_server`.`creative_group_coll` (`status_id` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ad_server`.`macros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ad_server`.`macros` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ad_server`.`macros` (
  `macros_id` INT NOT NULL,
  `macro_name` VARCHAR(100) NOT NULL,
  `macro_value` VARCHAR(100) NOT NULL,
  `account_id` INT NULL,
  `advertiser_id` INT NULL,
  `partner_id` INT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`macros_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `macros_acc_fk_idx` ON `ad_server`.`macros` (`account_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `macros_adv_fk_idx` ON `ad_server`.`macros` (`advertiser_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `macros_partner_fk_idx` ON `ad_server`.`macros` (`partner_id` ASC) ;

SHOW WARNINGS;
CREATE INDEX `macros_status_fk_idx` ON `ad_server`.`macros` (`status_id` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
